user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

email:
    resource: "@EmailBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

