<?php

namespace Quotera\EmailBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    /**
     * @return Email[]
     */
    public function getUpcomingEmails($max = null)
    {
        $qb = $this
                    ->createQueryBuilder('e')
                    ->addOrderBy('e.date', 'ASC')
                    ->andWhere('e.date > :now')
                    ->setParameter('now', new \DateTime());

        if($max)
        {
            $qb
                ->getQuery()
                ->execute();
        }
    }
}
