userinfo:
    path:     /
    defaults: { _controller: "UserBundle:userInfo:index" }

userinfo_show:
    path:     /{id}/show
    defaults: { _controller: "UserBundle:userInfo:show" }

userinfo_new:
    path:     /new
    defaults: { _controller: "UserBundle:userInfo:new" }

userinfo_create:
    path:     /create
    defaults: { _controller: "UserBundle:userInfo:create" }
    methods:  POST

userinfo_edit:
    path:     /{id}/edit
    defaults: { _controller: "UserBundle:userInfo:edit" }

userinfo_update:
    path:     /{id}/update
    defaults: { _controller: "UserBundle:userInfo:update" }
    methods:  [POST, PUT]

userinfo_delete:
    path:     /{id}/delete
    defaults: { _controller: "UserBundle:userInfo:delete" }
    methods:  [POST, DELETE]
